# Generated by Django 5.1 on 2024-09-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('type', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BetList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betId', models.CharField(max_length=20)),
                ('betPharseID', models.CharField(max_length=20)),
                ('betVal', models.IntegerField()),
                ('betChoice', models.CharField(max_length=20)),
                ('userName', models.CharField(max_length=20)),
                ('createAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BetPharse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betPharseID', models.CharField(max_length=20)),
                ('betResult', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createAt', models.DateField(auto_created=True)),
                ('userName', models.CharField(max_length=20)),
                ('ip', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('bankAccount', models.CharField(max_length=30)),
                ('bankName', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('status', models.IntegerField()),
                ('staffId', models.CharField(max_length=20)),
                ('activeAt', models.DateField(auto_now=True)),
            ],
        ),
    ]
