# Generated by Django 5.1 on 2024-09-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'managed': False},
        ),
    ]
